### ISSUE TITLE
SoapClient calls

### ISSUE THREAD

**Issue by GonzaloGPF** [viewflex/zoap#1]
I'm having problems trying to make requests using [SoapClient](http://php.net/manual/es/class.soapclient.php). I'm new to Soap and don't know how to configure it well.

I've tested it using Postman and works great but I cannot test it using SoapClient :(

I'm testing it using provided demo and this code:

```php
        ini_set('soap.wsdl_cache_enabled', 0);
        ini_set('soap.wsdl_cache_ttl', 900);
        ini_set('default_socket_timeout', 15);

        $params = array('user' => 'test@test.com', 'password' => 'tester');

        $wsdl = 'http://garages.test/soap/demo/server?wsdl';

        $options = array(
            'uri' => 'http://schemas.xmlsoap.org/soap/envelope/',
            'style' => SOAP_RPC,
            'use' => SOAP_ENCODED,
            'soap_version' => SOAP_1_1,
            'cache_wsdl' => WSDL_CACHE_NONE,
            'connection_timeout' => 15,
            'trace' => true,
            'encoding' => 'UTF-8',
            'exceptions' => true,
        );

        $headers = array();

        $headers[] = new SoapHeader('http://garages.test/soap/demo/server', 'Content-Type', 'application/xml');

        try {
            $client = new SoapClient($wsdl, $options);

            $client->__setSoapHeaders($headers);

            $data = $client->auth($params);
        } catch (Exception $e) {
            die($e->getMessage());
        }

        var_dump($data);
        die;
```
However, it returns me an error:

> [2018-05-09 07:51:16] local.INFO: #0 /home/vagrant/code/Garages/vendor/zendframework/zend-soap/src/Server.php(996): Zend\Soap\Server->fault(Object(Zend\Soap\Exception\BadMethodCallException))
#1 /home/vagrant/code/Garages/app/Http/Controllers/SOAP/SoapController.php(160): Zend\Soap\Server->handle()
#2 [internal function]: App\Http\Controllers\SOAP\SoapController->server('Content-Type')
#3 /home/vagrant/code/Garages/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /home/vagrant/code/Garages/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('server', Array)
...

Can I have an example using SoapClient? Is it possible? :S

Thanks!

**Comment by viewflex** [comment]
Using the package's demo route with your domain, this should return an object with an "authResult" property (an array of key/value pairs):

$client = new \Zend\Soap\Client('http://garages.test/zoap/demo/server?wsdl');
$result = $client->auth(['user' => 'test@test.com', 'password' =>'tester']);

Note that you used 'soap' rather than 'zoap' in your example - is that a typo or did you create a new route for that? If you are still having trouble, the Zend SOAP documentation contains some good examples of client configuration.

**Comment by vineetanand11** [comment]
Please use it.
$dataPOST = trim(file_get_contents('php://input'));  // this is the xml request 


        //$dataFromTheForm = $_POST['fieldName']; // request data from the form
        $soapUrl = "{{domain}}/zoap/demo/server"; // asmx URL of WSDL
        $soapUser = "test@test.com";  //  username
        $soapPassword = "tester"; // password

        // xml post structure
        $xml_post_string = $dataPOST;
        $headers = array(
                        "Content-type: text/xml;charset=\"utf-8\"",
                        "Accept: text/xml",
                        "Cache-Control: no-cache",
                        "Pragma: no-cache",
                        "SOAPAction: {{domain}}/zoap/demo/server", 
                        "Content-length: ".strlen($xml_post_string),
                    ); //SOAPAction: your op URL

            $url = $soapUrl;

            // PHP cURL  for https connection with auth
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_USERPWD, $soapUser.":".$soapPassword); // username and password - declared at the top of the doc
            curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
            curl_setopt($ch, CURLOPT_TIMEOUT, 10);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $xml_post_string); // the SOAP request
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            // converting
            $response = curl_exec($ch); 
            curl_close($ch);

            // converting
            $response1 = str_replace("<soap:Body>","",$response);
            $response2 = str_replace("</soap:Body>","",$response1);

            // convertingc to XML
            $parser = simplexml_load_string($response2);
            return $response2;
