### ISSUE TITLE
Failed to open stream: HTTP request failed

### ISSUE THREAD

**Issue by Dalot** [viewflex/zoap#11]
When I tried to access my endpoint on a Laravel Application(local) through ngrok(This is not the issue) I ended up with the following errors:

`PHP Warning:  SoapServer::SoapServer(http://7184fa0e.eu.ngrok.io/zoap/demo/server?wsdl): failed to open stream: HTTP request failed!  in C:\something\something\something\something\something\something\vendor\zendframework\zend-soap\src\Server.php on line 915
[Thu Jul  4 11:06:11 2019] PHP Warning:  SoapServer::SoapServer(): I/O warning : failed to load external entity &quot;http://7184fa0e.eu.ngrok.io/zoap/demo/server?wsdl&quot; in C:\something\something\something\something\something\something\vendor\zendframework\zend-soap\src\Server.php on line 915
[Thu Jul  4 11:06:11 2019] PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://7184fa0e.eu.ngrok.io/zoap/demo/server?wsdl' : failed to load external entity "http://7184fa0e.eu.ngrok.io/zoap/demo/server?wsdl"`

I was trying to debug to find out wha happened and as far as I could understand, this might be an infinite loop. If I make a request to `/zoap/demo/server?wsdl`, it returns the wsdl fine, although if I make a request to `/zoap/demo/server` it will be loading for 60s and then returns `PHP Fatal error:  Maximum execution time of 60 seconds exceeded` while blocking the `zoap/demo/server?wsdl` endpoint.

I tracked the code to find exactly where the loop would take place and it seems to be here:
`$server  = new SoapServer($this->wsdl, $options);`, `Server.php` file, `getSoap` Function. `$this->wsdl` is returning the wsdl URL as a string and `$options` an array with soap_version, so I guess they are working fine.

Out of curiosity I tried to deattach the `public function server($key)` in `ZoapController` in two, to fetch the `wsdl` on a different route and it resolved the infinite loop. Although, I ended up with an empty XML file. 

I am out of ideas and I would appreciate if someone would get back to me. Please do request additional information if you need it.

**EDIT:**
- laravel/framework: "5.6"
- PHP 7.3.5

**Comment by viewflex** [comment]
Hi @Dalot, sorry to take so long responding. I can't really think of an answer without having the same setup and the time to try that. I'll leave the question up for a while in case someone can help. Thanks for using the package and providing feedback.

**Comment by stephenlake** [comment]
Same problem with a default Laravel setup, nothing special.

**Comment by viewflex** [comment]
@stephenlake Are you also using a subdomain? Perhaps the suggested workaround here will help: [REQUEST_URI problem](https://github.com/viewflex/zoap/issues/6)

**Comment by stephenlake** [comment]
No subdomain in use, localhost on port 80. Calling the service just hangs at https://github.com/viewflex/zoap/blob/master/src/ZoapController.php#L161 and eventually gets killed by max execution time. 

Though this is more of a non-issue since I decided to use the regular PHP [SoapServer](https://www.php.net/manual/en/class.soapserver.php).

**Comment by viewflex** [comment]
@stephenlake I see, you are using localhost - I didn't plan on supporting that, but I suppose I should try to include it in the next update. Thanks for bringing that up!

**Comment by proAMD** [comment]
Encountered the same issue when I used the laravel dev server (http://localhost:8000). 
**Solution**:
Used xampp and configured a virtual host.

**Comment by sonius** [comment]
Stop
-------- Oorspronkelijk bericht --------Van: proAMD ***@***.***> Datum: 09-04-2021  7:08 a.m.  (GMT+10:00) Aan: viewflex/zoap ***@***.***> Cc: Subscribed ***@***.***> Onderwerp: Re: [viewflex/zoap] Failed to open stream: HTTP request failed (#11) 
Encountered the same issue when I used the laravel dev server (http://localhost:8000).
Solution:
Used xampp and configured a virtual host.
