### ISSUE TITLE
Have a custom route for the webservice

### ISSUE THREAD

**Issue by hypemedia** [viewflex/zoap#12]
Right now the web-service is responding on this URL.
domain-name.com/zoap/order/server/

Is there an way to have the web-service on a custom urls like this:
domain-name.com/mywebservice/

**Comment by viewflex** [comment]
You could create new routes, using 'mywebservice' as the route parameter.

```php
app()->router->get('/{key}', [
    'as' => 'zoap.server.wsdl',
    'uses' => '\Viewflex\Zoap\ZoapController@server'
]);

app()->router->post('/{key}', [
    'as' => 'zoap.server',
    'uses' => '\Viewflex\Zoap\ZoapController@server'
]);
```

This implies that you would also have a service class 'mywebservice' listed in the config.
