### ISSUE TITLE
Classmap usage

### ISSUE THREAD

**Issue by TimSmitsWork** [viewflex/zoap#14]
Hello,

Is it possible to have a php Classname different from the WSDL item name?
I thought thats where the Classmap from WSDL steps in? But it doesn't seem to to do much.

the default demo code has:

```
$wsdl = new Wsdl('wsdl', $this->endpoint);
foreach ($this->types as $key => $class) {
        $wsdl->addType($class, $key);
}
// Set type(s) on strategy object.
$this->strategy->setContext($wsdl);

foreach ($this->types as $key => $class) {
    $this->strategy->addComplexType($class);
}
```
You can pass a 4th item to the WSDL with classmap array, but it doesn't seem to do anything with it? i also edited some Zend code but didn't get any further..
It seems that the addType also overwrites the classMap in the addComplex type.. I tries leaving the addType away, but then i have some other errors about a arrayComplexItem not found in context etc..

The thing i want is:

We have a class `SoapItem` and when viewing the WSDL it also shows the `<xsd:complexType name="SoapItem">`
But i want to have the php Classname `SoapItem`, but have the WSDL to use `<xsd:complexType name="Item">`

Is that somewhat clear?

**Comment by viewflex** [comment]
@TimSmitsWork I will take a look at this over the weekend.

**Comment by TimSmitsWork** [comment]
Any idee @viewflex ?

**Comment by viewflex** [comment]
@TimSmitsWork I believe you are correct that `addType` will take precedence over `classMap`; it looks like the two methods are not meant to be used together. If you find a workaround, please let me know. Thanks for pushing the envelope!
