### ISSUE TITLE
security policy wsse

### ISSUE THREAD

**Issue by zabymarou** [viewflex/zoap#15]
Is there a way to add the wsse  security policy from http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd  to the generated wsdl and to handle a call where  a username and password were pass in the header?

**Comment by viewflex** [comment]
@zabymarou Interesting question. I will have to take a look when I get a chance, if no one else gets to it first. Please feel free to create a PR if you solve this. Thanks for trying the package!

**Comment by nicoworq** [comment]
Hi! First of all, thanks for this great library. 

I also need to implement wsse security policy. Did @zabymarou have the oportunity to implemented?

If not,  @viewflex can you please give me some directions to do this? 

Thanks in advance!! Best regards!
