### ISSUE TITLE
want to change the Soap response

### ISSUE THREAD

**Issue by arijitshiprocket** [viewflex/zoap#16]
in this getProducts() function  I get response as follows :
        <ns1:getProductsResponse>    
               <getProductsResult>     
                   <ns1:Product>       
                        <id>456</id>      
                          <name>North Face Summit Ski Jacket</name>
                           <category>Outerwear</category>
                            <subcategory>Women</subcategory>
                             <price>249.98</price>
                     </ns1:Product>
                     <ns1:Product>
                             <id>789</id>
                            <name>Marmot Crew Neck Base Layer</name>
                           <category>Outerwear</category>
                          <subcategory>Men</subcategory>
                          <price>95.29</price>
                     </ns1:Product>
                </getProductsResult>
        </ns1:getProductsResponse>

1.<ns1:getProductsResponse>     //change this name
2.<getProductsResult>     // change this name
3.<ns1:Product>        // this name
4. <id>456</id>       // want to change key name and make it from int to float.

see this commented section that i want change. for that i changed zoap.php and product.php file but it couldnot reflects. If any ideas please let me share...............................................

**Comment by viewflex** [comment]
@arijitshiprocket
1. 'Response' is added automatically to the method name.
2. ?
3. Change name of `Product` class to something else.
4. The key type will be whatever you define it as in the `Product` class.
