### ISSUE TITLE
Type array of another type

### ISSUE THREAD

**Issue by jerearaujo03** [viewflex/zoap#17]
How can I declare a type that it an array of another declared type? I want to customize his name.

**Comment by viewflex** [comment]
To declare a method parameter or return value as an array of a certain type, use `[]` after the type name. In the `DemoService` class, see the `getProducts()` DocBlock for an example:

```php
/**
 * Returns an array of products by search criteria.
 *
 * @param \Viewflex\Zoap\Demo\Types\KeyValue[] $criteria
 * @param string $token
 * @param string $user
 * @param string $password
 * @return \Viewflex\Zoap\Demo\Types\Product[]
 * @throws SoapFault
 */
public function getProducts($criteria = [], $token = '', $user = '', $password = '')
{...}
```
