### ISSUE TITLE
Get attributes?

### ISSUE THREAD

**Issue by stickeerehan** [viewflex/zoap#18]
Is there a way to get the attributes, especially those on the parent? 

For example see the following example SOAP request:

```
<soapenv:Body>
    <ser:OrderStatusNotification orderNumber="17282" statusCode="8" statusDetail="Order Despatched">
         <deliveryAddress name="Jon Doe" line1="6, Some Street" line2="" postcode="CW T"/>
    </ser:OrderStatusNotification>
</soapenv:Body>
```

When declaring the `OrderStatusNotification` function, the first attribute is actually `deliveryAddress`, and as far as I've been able to experiment and learn from the demo, this library doesn't allow me retrieve the attributes? Any idea @viewflex ?

**Comment by viewflex** [comment]
@stickeerehan Have you tried defining `deliveryAddress` as a type? Please see how `KeyValue` and `Product` are defined in the demo.
