### ISSUE TITLE
Cannot get response for an RPC type WSDL, always error

### ISSUE THREAD

**Issue by gaurravv5** [viewflex/zoap#19]
I want an RPC type WSDL, or Document type without any "sequence" element wrapper for the arguments. When I try to do so I never get response but error for passing "Content-header" as key for the wsdl.

**Comment by viewflex** [comment]
@gaurravv5 I had intended to support only the `document/literal wrapped` pattern in this package, but if you manage to create working examples of other patterns I will be happy to include that in the documentation.
