### ISSUE TITLE
Lumen

### ISSUE THREAD

**Issue by jmdavid** [viewflex/zoap#2]
Hello,

any plan to make it work with Lumen as well?

Thanks.

**Comment by viewflex** [comment]
It would require only a few small changes, so yes, it's a good idea and I imagine I'll get around to that shortly. Thanks for the suggestion.

**Comment by viewflex** [comment]
I just released [Zoap 1.0.2](https://github.com/viewflex/zoap/tree/1.0.2), which adds Lumen compatibility.
