### ISSUE TITLE
define namespaces

### ISSUE THREAD

**Issue by bcgarcia** [viewflex/zoap#20]
It's possible to define namespaces?

**Comment by Arielf14** [comment]
Good Morning.

Very good contribution, I get out of trouble.

I would like to know if there is a possibility to format the xml response for each method.
specifically something like this:

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <ns2:getDebtResponse>
            <return>
                <arrayData1>
                    <key1>
                        <id>NAME</id>
                        <value>Ariel</value>
                    </key1>
                    <key1>
                        <id>AGE</id>
                        <value>25</value>
                    </key1>
                    <key1>
                        <id>WEIGHT</id>
                        <value>85</value>
                    </key1>
                    <key2>ADDRESS</key2>
                    <key3>BIRTH_DATE</key3>
                </arrayData1>
                <codeResponse>0</codeResponse>
                <response>OK</response>
            </return>
        </ns2:getDebtResponse>
    </soap:Body>
</soap:Envelope>`

first time I use soap.

**Comment by bamorrison** [comment]
I too would like to know this information. Hopefully this is something that can be done with zoap.

**Comment by Gildus** [comment]
> It's possible to define namespaces?

Yes @bcgarcia  you can do it.

**Comment by renanwilliam** [comment]
> > It's possible to define namespaces?
> 
> Yes @bcgarcia you can do it.

And how do it?
