### ISSUE TITLE
XML Response Formats

### ISSUE THREAD

**Issue by arielfad** [viewflex/zoap#21]
Good Morning.

Very good contribution, I get out of trouble.

I would like to know if there is a possibility to format the xml response for each method.
specifically something like this:

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <getDebtResponse>
            <return>
                <arrayData1>
                    <key1>
                        <id>NAME</id>
                        <value>Ariel</value>
                    </key1>
                    <key1>
                        <id>AGE</id>
                        <value>25</value>
                    </key1>
                    <key1>
                        <id>WEIGHT</id>
                        <value>85</value>
                    </key1>
                    <ADDRESS>....</ADDRESS>
                    <BIRTH_DATE>....</BIRTH_DATE>
                </arrayData1>
                <codeResponse>0</codeResponse>
                <message>OK</message>
            </return>
        </getDebtResponse>
    </soap:Body>
</soap:Envelope>`

first time I use soap.

**Comment by Gildus** [comment]
Yes, you can follow the documentation in https://docs.laminas.dev/laminas-soap/server/
Remember use Docblock too.
