### ISSUE TITLE
Not working wsdl

### ISSUE THREAD

**Issue by Asepdadan** [viewflex/zoap#22]
run with laravel 7
php 7.3
and command php artisan serve --port 2020
and then response display in terminal

 PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://127.0.0.1:2020/zoap/demo/server?wsdl' : failed to load external entity "http://127.0.0.1:2020/zoap/demo/server?wsdl"
 in C:\xampp73\htdocs\createLaravelWsdl\vendor\zendframework\zend-soap\src\Server.php on line 914

need help

**Comment by Gildus** [comment]
> php artisan serve --port 2020

Hi @Asepdadan, you need to use the port 2020.

Sorry by the delay for this issue.

**Comment by yul-klj** [comment]
Actually i faced the same error
but mine was running in docker container
Laravel 5.6
php 7.2
php-soap installed
calling with SOAP-UI application

Application hosted with `php artisan serve --host 0.0.0.0 --port 8017`
Is that necessary to use php-fpm with nginx on top, or artisan serve could test it out successfully?

**Comment by yencolon** [comment]
Just initialize Server with WSDL param to null and make sure options have de Uri param of WSDL. 

`$options = ['uri' => endpoint]`
` $server = new Server(null, options);`
