### ISSUE TITLE
Middleware error

### ISSUE THREAD

**Issue by hypemedia** [viewflex/zoap#24]
Hi, 
I am getting this strange error PHP version is 7.1, Laravel Framework version 5.2.45

local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Viewflex\Zoap\ZoapController::getMiddleware() in /home/news.leaseplan.ro/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:110

thanks

**Comment by viewflex** [comment]
@hypemedia The `ZoapController` class does not extend the Laravel `Controller` class, so there is no middleware to get.
