### ISSUE TITLE
SoapServer create multi node

### ISSUE THREAD

**Issue by frans1skus** [viewflex/zoap#3]
Hi @viewflex, how to implementation multi-node from the findProduct method ?

**before response**

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://laravel-soap.develop/zoap/demo/server">
   <SOAP-ENV:Body>
      <ns1:getProductResponse>
         <getProductResult>
            <id>456</id>
            <name>North Face Summit Ski Jacket</name>
            <category>Outerwear</category>
            <subcategory>Women</subcategory>
            <price>249.98</price>
         </getProductResult>
      </ns1:getProductResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope> 

**which are expected**

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://laravel-soap.develop/zoap/demo/server">
   <SOAP-ENV:Body>
      <ns1:getProductResponse>
         <getProductResult>
            <id>456</id>
            <name>North Face Summit Ski Jacket</name>
            <category>
				<sample>
					<info>nice info</info>
					<description>nice to have</description>
				</sample>
			</category>
            <subcategory>Women</subcategory>
            <price>249.98</price>
         </getProductResult>
      </ns1:getProductResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

Thank you very much for the help,,

**Comment by viewflex** [comment]
I'm sorry, it's not clear to me exactly what result you're trying to get. The content of the demo responses is hard-coded, just to provide an example of the response format.

**Comment by frans1skus** [comment]
![using SoapUI](https://user-images.githubusercontent.com/8113413/40569862-71bc802a-60af-11e8-9540-9d4bdfbf04db.jpg)

How can i use from your code demo to give response just like the 'node category' in red highlight above ?

Thank you @viewflex for the help

**Comment by viewflex** [comment]
If I understand correctly, you want to define `category` as a standard object rather than a string, with `other_info` as a possible attribute of that object. This would be done in the `Product` class, by changing the type of the `category` attribute:

```php
/**
 * @var object
 */
public $category;
```


 ... and it's usage in the constructor:

```php
/**
 * Product constructor.
 *
 * @param int $id
 * @param string $name
 * @param object $category
 * @param string $subcategory
 * @param float $price
 */
public function __construct($id, $name = '', $category = null, $subcategory = '', $price = 0.00)
```

Your definitions can be as simple or complex as you need; it's all in the docblocks.

**Comment by frans1skus** [comment]
Hi, @viewflex 
It works,,

Thank You Very Much for your Time & Help,,
