### ISSUE TITLE
Unable to set soap_version

### ISSUE THREAD

**Issue by tonila** [viewflex/zoap#5]
Hi,

This package seems to use zend-soap. I could not find any way of setting zend-soap options, e.g. soap_version.

Is there any way of setting options?

**Comment by viewflex** [comment]
I do think it would be useful to have an options array in the package config - thank you for the suggestion, I will include that in the next release! Meanwhile, you could extend the controller and override the server() method to include setting options.

**Comment by tonila** [comment]
Thx!
I did overrode server() method.
