### ISSUE TITLE
REQUEST_URI problem

### ISSUE THREAD

**Issue by hypemedia** [viewflex/zoap#6]
Hi
I am running the laravel install inside an folder of a domain:

name.domain.xx/carstatus/

Everything in the laravel app works but when requesting the SOAP server route:
name.domain.xx/carstatus/zoap/Client_data/server

I get an error because of the missing wsdl. The problem is related to the url:

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://name.domain.xx/carstatus/carstatus/zoap/Client_data/server?wsdl' : failed to load external entity "https://name.domain.xx/carstatus/public/carstatus/zoap/Client_data/server?wsdl"

The problem is that the 'carstatus' where laravel is installed shows an extra time. I think is because of public static function currentUrlRoot() but not sure how to fixit.

This is my .htaccess:

```
RewriteEngine On


     RewriteCond %{REQUEST_FILENAME} -d [OR]
     RewriteCond %{REQUEST_FILENAME} -f
     RewriteRule ^ ^$1 [N]

     RewriteCond %{REQUEST_URI} (\.\w+$) [NC]
     RewriteRule ^(.*)$ public/$1

     RewriteCond %{REQUEST_FILENAME} !-d
     RewriteCond %{REQUEST_FILENAME} !-f
     RewriteRule ^ server.php

     RewriteBase /carstatus
```

And this is the info from .env file:

APP_URL=https://name.domain.xx/carstatus/

Any ideas on what can be done to make it work?

If I go on the browser directly on the https://name.domain.xx/carstatus/carstatus/zoap/Client_data/server?wsdl
it works

I have 2 laravel installs on same subdomain:
The first is on the root
https://name.domain.xx/

The scond one that has this problem is inside the folder carstatus.

All the config is ok as both apps are running. The SOAP server is the only exception.

**Comment by hypemedia** [comment]
Inside the ZoapController.php if i change the line:

`$url = url(app()->request->server()['REQUEST_URI']);`

to 
`$url = url()->full();`

It works but not sure it is ok to do this

**Comment by viewflex** [comment]
Thanks for the question. Regarding using `url()->full()`, the `url()` helper method can return a `UrlGenerator` instance or a string in Laravel, so your workaround may not work in all cases. In Lumen only a string is returned, so it won't work at all. I haven't tested this package on a subdomain, and I'm not sure if having one project inside the root of another might be causing your issue. I would be interested to know if there is a better way, compatible with both Laravel and Lumen, to consistently derive the correct URI, even in your specific use cases.

**Comment by aamson** [comment]
Inside the ZoapController.php if i change the line:
$this->endpoint = self::currentUrlRoot();

to:
$this->endpoint = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

It works for me but I'm not sure if it works for for all.
