### ISSUE TITLE
Generating wsdl with nillable and minOccurs

### ISSUE THREAD

**Issue by hypemedia** [viewflex/zoap#7]
Is there any way to generate the WSDL with nillable and minOccurs? I was not able to find a way.
`<xs:element minOccurs="0" name="NumberTires" nillable="true" type="xs:int"/>`

**Comment by viewflex** [comment]
@hypemedia This package does generate the nillable attribute based on DocBlock annotation and method signature (see the demo). Regarding minOccurs and maxOccurs, I found this annotation hack for the Zend component, perhaps it still works:

http://zend-framework-community.634137.n4.nabble.com/Zend-Soap-Autodiscover-how-to-generate-minOccurs-and-maxOccurs-in-WSDL-td675932.html#a675934

**Comment by hypemedia** [comment]
Ok thanks fo the info that will work. But custom headers is it possible to generate?
 Something like that:

`<soapenv:Header>
         <esb:header>
            <esb:message_type>AddNewOrder</esb:message_type>
            <esb:version>01.80</esb:version>
            <esb:source_entity>LPRO</esb:source_entity>
            <esb:source_application>NOLS</esb:source_application>
            <esb:destination_entity>KEIT</esb:destination_entity>
            <esb:destination_application>TIRE</esb:destination_application>
         </esb:header>
</soapenv:Header>`

**Comment by viewflex** [comment]
@hypermedia If you mean returning custom headers with the response, you could extend the controller and override the `server()` method to perform XML post-processing before returning it.

**Comment by hypemedia** [comment]
No the problem is that in the request that we get on the server it is sent an soap header like this:

`<soapenv:Header> <esb:header> <esb:message_type>AddNewOrder</esb:message_type> <esb:version>01.80</esb:version> <esb:source_entity>LPRO</esb:source_entity> <esb:source_application>NOLS</esb:source_application> <esb:destination_entity>KEIT</esb:destination_entity> <esb:destination_application>TIRE</esb:destination_application> </esb:header> </soapenv:Header>`

The problem is that the requesti is failing because of that header. Is there an way to define that header in the wsdl. The soap header element is part of the SOAP specifications.

**Comment by viewflex** [comment]
Now I understand - that header (for an ESB proxy?) is part of a request format you can't change, so the server must accept it. 

I could not find any way to achieve this via auto-discovery (please let me know if you do), but there are a few guides on [IBM](https://www.ibm.com/developerworks/library/ws-tip-headers/index.html) and [RedHat](https://access.redhat.com/documentation/en-US/Fuse_ESB_Enterprise/7.1/html/Using_the_Web_Services_Bindings_and_Transports/files/ContractSOAP11Headers.html) sites, and [this example](https://nitinaggarwal.wordpress.com/2010/12/08/adding-a-custom-header-to-your-web-service-wsdl/), explaining how to manually map a SOAP request header in WSDL.

It seems the solution is to override the `server()` method, adding post-processing of the generated WSDL file, inserting the necessary request header mapping.

**Comment by hypemedia** [comment]
Thanks I will get back if I find a way of doing this with auto-discovery.

**Comment by viewflex** [comment]
@hypemedia Thanks, and good luck!
