### ISSUE TITLE
foldername is repeating 

### ISSUE THREAD

**Issue by manumonrh** [viewflex/zoap#9]
when am creating wsdl file is correct but the folder name is repeating  **api/api** xmlns:tns="http://example.com/**api/api**/zoap/demo/server"
 so we can't call soap client service from local or server.

like : http://localhost/blog/public/index.php/blog/public/index.php/zoap/demo/server

**Comment by viewflex** [comment]
@manumonrh - If you could provide a bit more info on your routing setup... not sure if this issue is similar but perhaps the suggested workaround will help: [REQUEST_URI problem](https://github.com/viewflex/zoap/issues/6)
